# [作業目標]
- 利用範例的創建方式, 創建一組資料, 並練習如何取出最大值

# [作業重點]
- 練習創立 DataFrame (In[2])
- 如何取出口數最多的國家 (In[3], Out[3])

## 練習時間
在小量的資料上，我們用眼睛就可以看得出來程式碼是否有跑出我們理想中的結果

請嘗試想像一個你需要的資料結構 (裡面的值可以是隨機的)，然後用上述的方法把它變成 pandas DataFrame

#### Ex: 想像一個 dataframe 有兩個欄位，一個是國家，一個是人口，求人口數最多的國家

### Hints: [隨機產生數值](https://blog.csdn.net/christianashannon/article/details/78867204)

In [0]:
import pandas as pd
import numpy as np

In [0]:
data = {'國家':['Taiwan','USA','Japan','Korea','Indonesia','Malysia','Singapore','Tailand'] ,
        '人口':np.random.randint(1000000, 100000000, 8) }
data = pd.DataFrame(data)

In [3]:
print(data)

          國家        人口
0     Taiwan   6017487
1        USA  14771101
2      Japan  46836951
3      Korea   4497573
4  Indonesia  35125521
5    Malysia  45500485
6  Singapore  53499742
7    Tailand  18295932

In [4]:
data.iloc[data[['人口']].idxmax()]

          國家        人口
6  Singapore  53499742